{
 "title": "java-tron-api-statistic",
 "tags": [ "java-tron" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "group", "label": "group", "query": { "query": "label_values(group)" } }
  ]
 },
 "panels": [
  {
   "title": "Low Perf API Alert-getBlocksByLimitNext(http)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tron:http_service_latency_seconds_count{group=`$group`,url='/wallet/getblockbylimitnext'}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Low Perf API Alert-getBlocksByLimitNext(grpc)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tron:grpc_service_latency_seconds_count{group=`$group`,endpoint=`protocol.Wallet/GetBlockByLimitNext`}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Low Perf API Alert-getAssetIssueList",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tron:internal_service_latency_seconds_count{group=`$group`,class=\"Wallet\",method =\"getAssetIssueList\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Low Perf API Alert-getBlockByLatestNum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tron:internal_service_latency_seconds_count{group=`$group`,class=\"Wallet\",method =\"getBlockByLatestNum\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "getTransactionById QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tron:internal_service_latency_seconds_count{group=`$group`,class=\"Wallet\",method =\"getTransactionById\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "getTransactionInfoById QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tron:internal_service_latency_seconds_count{group=`$group`,class=\"Wallet\",method =\"getTransactionInfoById\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "getAccount QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tron:internal_service_latency_seconds_count{group=`$group`,class=\"Wallet\",method =\"getAccount\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "getTransactionInfoByBlockNum QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(tron:internal_service_latency_seconds_count{group=`$group`,class=\"Wallet\",method =\"getTransactionInfoByBlockNum\"}[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " HTTP QPS Total of all instances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tron:http_service_latency_seconds_count{group=`$group`}[$__rate_interval])) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": " GRPC QPS Total of all instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(tron:grpc_service_latency_seconds_count{group=`$group`}[$__rate_interval])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}