# [[nodes]]
# node_ip = "192.168.1.1" # Remote node's IP
# node_directory = "/path/to/direcotry" # Remote node's working direcotry for node
# config_file = "/path/to/config" # Config file for remote node
# docker_compose_file =”/path/to/config“ # Config  docker-compose  file for remote node
# node_type = "fullnode/sr" # Fullnode or SR node
# ssh_port = 22
# ssh_user = "user1"
# ssh_password = "password1" # Optional; uncomment if using password auth
# # ssh_key = "/path/to/key1"  # Optional; uncomment if using key auth

# [[nodes]]
# node_ip = "192.168.1.2"  # Changed IP to demonstrate different nodes
# node_directory = "/path/to/directory"
# config_file = "/path/to/config"
# docker_compose_file =”/path/to/config“ # Config  docker-compose  file for remote node
# node_type = "fullnode/sr"
# ssh_port = 2222  # Custom SCP port for this node
# ssh_user = "user2"
# # No password or key; assumes SSH agent or pre-configured key


[[nodes]]
node_ip = "ec2-3-25-116-244.ap-southeast-2.compute.amazonaws.com"
node_directory = "/home/ubuntu/mytest"
config_file = "/Users/ubuntu/conf/private_net_config_others.conf"
docker_compose_file = "/Users/ubuntu/docker-compose.yml"
ssh_port = 22
ssh_user = "ubuntu"
# ssh_password = "password1"
ssh_key = "/Users/ubuntu/Downloads/test-ci.pem"  # Optional; uncomment if using key auth
